### PR TITLE
Send regions to the inferior REPL in paste mode.

### PR DESCRIPTION
**Pull request by ieure**
Thank you for contributing to ENSIME!

If this is your first time submitting a PR, this is what you can expect:

1. You'll have to agree to the licences we use. You'll get a link to follow in a moment.
2. Your code will be automatically tested. That can take as long as an hour before the results come back. You can read `.drone.yml` to see what is being run.
3. We'll try to review your code and give feedback quickly.
4. Please squash your commits into independent units. We use the commit log as our changelog so it is good if your commit messages are clear and concise.
5. You can request an ENSIME sticker from `@fommil`, be sure to ask if you want one!
6. If everything goes silent, please ping us.

Now, delete this line and everything above it, then tell us which tickets this PR closes (please don't reference tickets directly from your commit messages).

If you send a piece of code containing forward references, simply
dumping it into the REPL doesn’t work because, it processes each
definition individually. Enabling paste mode, this allows the REPL to
correctly deal with this situation.

### CODE REVIEW

**Comment by fommil** [comment]
Cool. Gold you come up with an automated test for this please?

**Comment by fommil** [comment]
#383 might need fixing for this to be useable

**Comment by ieure** [comment]
> Cool. Could you please come up with an automated test for this?

I don't think the effort is warranted, any test would be both heavy (due to needing to create a process and buffer to send a region of) and brittle, due to duplicating code in the actual function.

> #383 might need fixing for this to be useable

I can't reproduce this issue. Both manually entering paste mode and my changes in this PR work fine.

**Comment by fommil** [comment]
@ieure if it doesn't have a test, then you can't expect it to keep working and we put a lot of effort into testing so I disagree with your diagnosis. This is documented in the contributing page if you'd like to learn more.

I'll leave this PR here until you have a think about testing. We're a mature project now and testing is important to us.

**Comment by ieure** [comment]
Okay, never mind then.

**Pull request closed without merging**
