### PR TITLE
Add tests of the type inspector UI

### PR DESCRIPTION
**Pull request by aemoncannon**

### CODE REVIEW

**Comment by aemoncannon** [comment]
Looks like our old friend 'spurious non-zero status'...

**Comment by fommil** [comment]
hmm, but on all the branches?

**Comment by aemoncannon** [comment]
so confused by this: we print status is 1, which means that
ensime--test-had-failures must be true, but how can
ensime--test-had-failures be true if no test failed? something weird going
on.

**Comment by aemoncannon** [comment]
Working theory: there *is* a failing test, but somehow we're not logging it.

**Comment by fommil** [comment]
I've made the build matrix only for two versions of emacs, can you rebase please?

**Pull request closed without merging**
