### PR TITLE
Events to make it easier to test REPL interactions.

### PR DESCRIPTION
**Pull request by dangerousben**

### CODE REVIEW

**Comment by dangerousben** [comment]
@fommil are there instructions for replicating the shippable build locally somewhere?  I've built a container from ensime-docker but now I'm a bit stuck.

**Comment by fommil** [comment]
yeah, it sucks. They run some proprietary scripts. I'm hoping to move us over to drone, which is both conceptually easier and all open source.

It should be just as simple as cloning the repo and running the shell commands in the `shippable.yml` file.

**Comment by fommil** [comment]
I'm seeing this on shippable

```
Starting test: 'REPL without server.'
Copying /tmp/ensime_test_proj_226vJf/cache to /tmp/ensime_test_proj_226JzH/cache
(void-function string-suffix-p) error in process filter: or
```

**Comment by aemoncannon** [comment]
string-suffix-p was introduced in 24.4 -- could that be the cause?

**Comment by fommil** [comment]
of course, we matrix test back to 24.1

**Comment by fommil** [comment]
maybe there is something in dash?

**Comment by aemoncannon** [comment]
s.el has s-ends-with?

**Comment by fommil** [comment]
sorry, I didn't realise you'd rebased.

**Pull request merged**
