### PR TITLE
Use short type names in company-mode templates.

### PR DESCRIPTION
**Pull request by jmpage**
Resolves ensime/ensime-emacs#463

### CODE REVIEW

**Comment by fommil** [comment]
Thanks! Everybody will notice this one.

**Comment by fommil** [comment]
(also Vim fixed this last week, and we can't possibly let them have anything we don't have)

**Comment by jmpage** [comment]
I completely agree :wink:

**Comment by fommil** [comment]
this has been released http://melpa.org/#/ensime

**Pull request merged**
