### PR TITLE
use JDK_HOME if available

### PR DESCRIPTION
**Pull request by fommil**
https://github.com/ensime/ensime-server/pull/829

### CODE REVIEW

**Comment by aemoncannon** [comment]
Lgtm

**Comment by aemoncannon** [comment]
So this is for emacs 23 compat? Package el ships with 24 right?

**Comment by fommil** [comment]
yay! Coverage working in pull requests

**Comment by aemoncannon** [comment]
Yes!

**Comment by rorygraves** [comment]
Cool stuff.

**Pull request merged**
