### PR TITLE
Show std output for ensime-update process.

### PR DESCRIPTION
**Pull request by aemoncannon**

### CODE REVIEW

**Comment by aemoncannon** [comment]
@fommil This might be the hang you were seeing? Looks like can't resolve some scala jars...


[info] 	[SUCCESSFUL ] org.codehaus.plexus#plexus-utils;1.5.6!plexus-utils.jar (173ms)
[info] downloading https://repo1.maven.org/maven2/org/apache/maven/scm/maven-scm-provider-svn-commons/1.4/maven-scm-provider-svn-commons-1.4.jar ...
[info] 	[SUCCESSFUL ] org.apache.maven.scm#maven-scm-provider-svn-commons;1.4!maven-scm-provider-svn-commons.jar (152ms)
[info] downloading https://repo1.maven.org/maven2/regexp/regexp/1.3/regexp-1.3.jar ...
[info] 	[SUCCESSFUL ] regexp#regexp;1.3!regexp.jar (442ms)
[info] downloading https://repo1.maven.org/maven2/org/ow2/asm/asm-tree/5.0.3/asm-tree-5.0.3.jar ...
[info] 	[SUCCESSFUL ] org.ow2.asm#asm-tree;5.0.3!asm-tree.jar (585ms)
[info] downloading https://repo1.maven.org/maven2/org/ow2/asm/asm/5.0.3/asm-5.0.3.jar ...
[info] 	[SUCCESSFUL ] org.ow2.asm#asm;5.0.3!asm.jar (181ms)
[info] downloading https://repo1.maven.org/maven2/ch/qos/logback/logback-core/1.1.2/logback-core-1.1.2.jar ...
[info] 	[SUCCESSFUL ] ch.qos.logback#logback-core;1.1.2!logback-core.jar (85ms)
[info] downloading https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.9/slf4j-api-1.7.9.jar ...
[info] 	[SUCCESSFUL ] org.slf4j#slf4j-api;1.7.9!slf4j-api.jar (238ms)
[info] downloading https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.11.4/scala-compiler-2.11.4.jar ...
[warn] 	[FAILED     ] org.scala-lang#scala-compiler;2.11.4!scala-compiler.jar: Connection reset (1827ms)
[warn] 	[FAILED     ] org.scala-lang#scala-compiler;2.11.4!scala-compiler.jar: Connection reset (1827ms)
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.11.4/scala-compiler-2.11.4.jar
[info] downloading https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.11.4/scala-reflect-2.11.4.jar ...
[info] 	[SUCCESSFUL ] org.scala-lang#scala-reflect;2.11.4!scala-reflect.jar (1406ms)
[info] downloading https://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar ...
[info] 	[SUCCESSFUL ] org.scala-lang.modules#scala-xml_2.11;1.0.2!scala-xml_2.11.jar(bundle) (112ms)
[info] downloading https://repo1.maven.org/maven2/org/scala-lang/modules/scala-parser-combinators_2.11/1.0.2/scala-parser-combinators_2.11-1.0.2.jar ...
[info] 	[SUCCESSFUL ] org.scala-lang.modules#scala-parser-combinators_2.11;1.0.2!scala-parser-combinators_2.11.jar(bundle) (123ms)
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::              FAILED DOWNLOADS            ::
[warn] 	:: ^ see resolution messages for details  ^ ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: org.scala-refactoring#org.scala-refactoring.library_2.11;0.6.2!org.scala-refactoring.library_2.11.jar
[warn] 	:: org.scala-lang#scala-compiler;2.11.4!scala-compiler.jar
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
sbt.ResolveException: download failed: org.scala-refactoring#org.scala-refactoring.library_2.11;0.6.2!org.scala-refactoring.library_2.11.jar
download failed: org.scala-lang#scala-compiler;2.11.4!scala-compiler.jar
	at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:278)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:175)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:157)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:151)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:151)
	at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:128)
	at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:56)
	at sbt.IvySbt$$anon$4.call(Ivy.scala:64)
	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
	at xsbt.boot.Using$.withResource(Using.scala:10)
	at xsbt.boot.Using$.apply(Using.scala:9)
	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
	at xsbt.boot.Locks$.apply0(Locks.scala:31)
	at xsbt.boot.Locks$.apply(Locks.scala:28)
	at sbt.IvySbt.withDefaultLogger(Ivy.scala:64)
	at sbt.IvySbt.withIvy(Ivy.scala:123)
	at sbt.IvySbt.withIvy(Ivy.scala:120)
	at sbt.IvySbt$Module.withModule(Ivy.scala:151)
	at sbt.IvyActions$.updateEither(IvyActions.scala:157)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1318)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1315)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$85.apply(Defaults.scala:1345)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$85.apply(Defaults.scala:1343)
	at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:35)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1348)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1342)
	at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:45)
	at sbt.Classpaths$.cachedUpdate(Defaults.scala:1360)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1300)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1275)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1146)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:701)
[error] (*:update) sbt.ResolveException: download failed: org.scala-refactoring#org.scala-refactoring.library_2.11;0.6.2!org.scala-refactoring.library_2.11.jar
[error] download failed: org.scala-lang#scala-compiler;2.11.4!scala-compiler.jar
[error] Total time: 40 s, completed Feb 16, 2015 6:25:14 PM
Process *ensime-update* exited: exited abnormally with code 1

**Comment by fommil** [comment]
no, mine hangs after several tests... I think it's the debugging test that hangs. It's almost like it's not closing down when its finished.

**Comment by rorygraves** [comment]
Emacs jenkins sees:

```Starting test: 'Test inspect type at point.'
Debugger entered!
  (signal error (Invalid version string: 'nil'))
  ((lambda (reason &optional arg2) (message Debugger entered!) (let* ((i 3) (frame (backtrace-frame i))) (while frame (message   %s (cdr frame)) (setq i (+ i 1)) (setq frame (backtrace-frame i))))) error (error Invalid version string: 'nil'))
  (signal error (Invalid version string: 'nil'))
  (error Invalid version string: '%s' nil)
 ```

http://fieldmarkeng.co.uk/job/Ensime-Emacs-CI-Build-PR-Builder/29/console

Latest CI build has the same error:

http://213.136.89.60:8080/job/Ensime-Emacs-CI-Build/47/console

Related?

**Comment by fommil** [comment]
this error just looks like a transient downloading problem. That surely must only happen if the entire ivy cache is being recreated from maven central.

**Comment by aemoncannon** [comment]
mm makes sense

**Comment by aemoncannon** [comment]
Merging this, as the failure is unrelated and this will help debug.

**Pull request merged**
