### PR TITLE
update SNAPSHOT info

### PR DESCRIPTION
**Pull request by mpollmeier**
as discussed in https://github.com/ensime/ensime-emacs/pull/516

### CODE REVIEW

**Comment by fommil** [comment]
The wording looks good! But you're missing some quote escapes. I have no idea how the build succeeded.

**Comment by fommil** [comment]
:smile:

**Comment by mpollmeier** [comment]
whoops - only just tested locally and those quotes completely killed ensime... fixed now

**Comment by fommil** [comment]
Lgtm

**Pull request merged**
