### PR TITLE
Get classpath for repl from config rather than server, and remove dependency on scala binary

### PR DESCRIPTION
**Pull request by dangerousben**
Two potential issues with this:

 * I don't fully understand the .ensime format so what I've done is a guess based on what ensime-sbt generates
 * The repl starts up with the following error:
Failed to created JLineReader: java.lang.NoClassDefFoundError: jline/console/completer/Completer
Falling back to SimpleReader.

jline is in SCALA_HOME/lib so I'm not sure how to locate it.  But then since completion doesn't work anyway perhaps this isn't a problem?

### CODE REVIEW

**Comment by fommil** [comment]
Cool, thanks! I have an issue with my eyes at the moment and can't review for a week or so. So please don't take lack of feedback as a bad sign, this feature is on the 1.0 roadmap so  we're very keen to get it merged.

**Comment by edani** [comment]
@dangerousben I'd also like to look at this in more detail (in a day or two). Here's a preliminary remark: does it make sense to remove the emacs `ensime-rpc-repl-config` if it isn't used any more? Also a unit test (in the fast-test-suite) for the new `ensime-inf-repl-config` would be good.

**Comment by dangerousben** [comment]
On 3 May 2015 at 20:04, Eric Daniel <notifications@github.com> wrote:
> @dangerousben I'd also like to look at this in more detail (in a day or
> two). Here's a preliminary remark: does it make sense to remove the emacs
> ensime-rpc-repl-config if it isn't used any more?

Yep, probably.  And possibly even to remove the support from the
server, but I don't know whether there are other clients out there
relying on it.

> Also a unit test (in the
> fast-test-suite) for the new ensime-inf-repl-config would be good.

Good point.  I'm not really experienced with unit testing in elisp,
but I'll give it a go.

Ben

**Comment by edani** [comment]
@dangerousben  I see quite a few differences between then old and new behavior:

1) the scala invoker passes extra options to Java, namely:
```-Xmx256M -Xms32M
-classpath  contains all the jars in $SCALA_HOME/lib
-Dscala.home="$SCALA_HOME"
-Dscala.usejavacp=true
```
I don't know for sure what all of them do but they're probably important.

2) the new behavior adds all of Ensime's jars to the classpath, I don't think they're needed at all

**Comment by fommil** [comment]
It would probably be safe to pass the project's JVM flags instead of using the arbitrary ones that the script uses. They are in the `.ensime` file.... with a fallback. That way if the project needs a higher than usual `-Xms` then the REPL will use it also.

**Comment by dangerousben** [comment]
On 6 May 2015 at 07:43, Eric Daniel <notifications@github.com> wrote:
> @dangerousben I see quite a few differences between then old and new
> behavior:

> -classpath contains all the jars in $SCALA_HOME/lib
> -Dscala.home="$SCALA_HOME"

Problem is I can't see an easy way to get hold of $SCALA_HOME, the
rest of ensime doesn't appear to require it.

**Comment by dangerousben** [comment]
On 6 May 2015 at 07:43, Eric Daniel <notifications@github.com> wrote:
> @dangerousben I see quite a few differences between then old and new
> behavior:
>
> -Dscala.usejavacp=true

I guess this is just an easier alternative to passing in the classpath
twice as I am currently, I'll try it and see.

**Comment by fommil** [comment]
I don't think SCALA_HOME is needed. sbt is able to start a REPL fine without it.

**Comment by fommil** [comment]
re: scala compiler libs, you can get those by scanning the ensime classpath and extracting the files that you need (it'll probably just be scala-compiler and possibly jline, which we might not depend on but we could do if needed).

**Comment by fommil** [comment]
jline is a java library, you could add the latest release (don't get confused that the releases are by, sort-of, coincidentally similar to scala version numbers) to the list of `build.sbt` that we run during `ensime-update`. Then you could scan for it.

**Comment by dangerousben** [comment]
On 9 May 2015 at 22:20, Sam Halliday <notifications@github.com> wrote:
> jline is a java library, you could add the latest release (don't get
> confused that the releases are by, sort-of, coincidentally similar to scala
> version numbers) to the list of build.sbt that we run during ensime-update.
> Then you could scan for it.

Is it necessary though?  It provides readline-like functionality which
we get from emacs anyway.

**Comment by fommil** [comment]
re: jline. I'd assumed it was a required dependency, if you can start the REPL without it then that's great! Yes, we can focus on improving the scala repl mode in such a case.

**Comment by fommil** [comment]
I gave this a try and the REPL started, yay! But the project jars aren't on the classpath.

I basically just did an `import shapeless._` in the `ensime-server` project.

**Comment by fommil** [comment]
re: `-Dscala.usejavacp=true` it's a magical thing. It means to pass the java process' classpath to the scala compiler process. If you can, it would be best not to use it, but it might just be easier to leave it for now.

**Comment by dangerousben** [comment]
That is odd, it works for me (TM).  Could you let me know what (ensime-inf-repl-config) gives you?

**Comment by fommil** [comment]
doh! I'm an idiot, I thought "oh, we don't depend on the server anymore so we can do this without starting a server". But of course we need to select a config file and we do that by starting the server. Starting the server up, it works. Awesome stuff! When you're happy with this can you please squash? Eric or Aemon are much better at the emacs stuff than me, so I'll wait for one of them to review.

**Comment by fommil** [comment]
hmm,

```
Failed to created JLineReader: java.lang.NoClassDefFoundError: jline/console/completer/Completer
Falling back to SimpleReader.
Welcome to Scala version 2.11.4 (Java HotSpot(TM) 64-Bit Server VM, Java 1.6.0_45).
```

I can understand the jline error... bit why is it using scala 2.11.4 instead of my project's 2.11.6?

**Comment by fommil** [comment]
printing out the classpath to `*Messages*` until we're happy with the PR might be useful for debugging.

**Comment by dangerousben** [comment]
On 10 May 2015 at 11:28, Sam Halliday <notifications@github.com> wrote:
> I can understand the jline error... bit why is it using scala 2.11.4 instead
> of my project's 2.11.6?

Not sure.  Things to check:

:scala-version in .ensime
compiler jar listed in ensime's classpath file for that scala version
the compiler jar in :compile-deps in .ensime (since for ensime-server
it's a dependency anyway)

**Comment by fommil** [comment]
both v2.11.6. I'm trying to print the classpath info to the messages to understand more.

**Comment by fommil** [comment]
```
Launching REPL: (/usr/lib/jvm/java-6-oracle/bin/java -XX:MaxPermSize=384m -Xms512m -Xmx1536m -Xss2m -XX:ReservedCodeCacheSize=256m -XX:+TieredCompilation -XX:+CMSClassUnloadingEnabled -XX:+UseConcMarkSweepGC -classpath /home/fommil/.ivy2/cache/org.scala-lang/scala-compiler/jars/scala-compiler-2.11.6.jar:/home/fommil/.ivy2/cache/org.scala-lang/scala-reflect/jars/scala-reflect-2.11.6.jar::/home/fommil/Projects/ensime-server/testing/docs/target/scala-2.11/classes:/home/fommil/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.11.4.jar:/home/fommil/.ivy2/cache/com.google.guava/guava/bundles/guava-18.0.jar:/home/fommil/.ivy2/cache/com.github.dvdme/ForecastIOLib/jars/ForecastIOLib-1.5.1.jar:/home/fommil/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.11.6.jar:/home/fommil/.ivy2/cache/com.eclipsesource.minimal-json/minimal-json/bundles/minimal-json-0.9.1.jar:/home/fommil/.ivy2/cache/org.scoverage/scalac-scoverage-runtime_2.11/jars/scalac-scoverage-runtime_2.11-1.0.4.jar:/home/fommil/.ivy2/cache/org.scoverage/scalac-scoverage-plugin_2.11/jars/scalac-scoverage-plugin_2.11-1.0.4.jar:/home/fommil/.ivy2/cache/org.scala-lang.modules/scala-xml_2.11/bundles/scala-xml_2.11-1.0.1.jar:/home/fommil/.ivy2/cache/commons-io/commons-io/jars/commons-io-2.4.jar:/home/fommil/Projects/ensime-server/sexpress/target/scala-2.11/classes:/home/fommil/.ivy2/cache/com.chuusai/shapeless_2.11/bundles/shapeless_2.11-2.2.0-SNAPSHOT.jar:/home/fommil/.ivy2/cache/com.github.stacycurl/pimpathon-core_2.11/jars/pimpathon-core_2.11-1.5.0-SNAPSHOT.jar:/home/fommil/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.11.4.jar:/home/fommil/.ivy2/cache/org.scala-lang/scala-reflect/jars/scala-reflect-2.11.6.jar:/home/fommil/.ivy2/cache/org.parboiled/parboiled-scala_2.11/jars/parboiled-scala_2.11-1.1.7.jar:/home/fommil/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.11.6.jar:/home/fommil/.ivy2/cache/org.scoverage/scalac-scoverage-runtime_2.11/jars/scalac-scoverage-runtime_2.11-1.0.4.jar:/home/fommil/.ivy2/cache/org.parboiled/parboiled-core/jars/parboiled-core-1.1.7.jar:/home/fommil/.ivy2/cache/org.scoverage/scalac-scoverage-plugin_2.11/jars/scalac-scoverage-plugin_2.11-1.0.4.jar:/home/fommil/.ivy2/cache/org.scala-lang.modules/scala-xml_2.11/bundles/scala-xml_2.11-1.0.1.jar:/home/fommil/Projects/ensime-server/target/scala-2.11/classes:/home/fommil/Projects/ensime-server/testing/empty/target/scala-2.11/classes:/home/fommil/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.11.4.jar:/home/fommil/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.11.6.jar:/home/fommil/.ivy2/cache/org.scoverage/scalac-scoverage-runtime_2.11/jars/scalac-scoverage-runtime_2.11-1.0.4.jar:/home/fommil/.ivy2/cache/org.scoverage/scalac-scoverage-plugin_2.11/jars/scalac-scoverage-plugin_2.11-1.0.4.jar:/home/fommil/.ivy2/cache/org.scala-lang.modules/scala-xml_2.11/bundles/scala-xml_2.11-1.0.1.jar:/home/fommil/Projects/ensime-server/server/target/scala-2.11/classes:/home/fommil/.ivy2/cache/org.scala-refactoring/org.scala-refactoring.library_2.11/jars/org.scala-refactoring.library_2.11-0.6.2.jar:/home/fommil/.ivy2/cache/com.google.guava/guava/bundles/guava-15.0.jar:/home/fommil/.ivy2/cache/commons-lang/commons-lang/jars/commons-lang-2.6.jar:/home/fommil/.ivy2/cache/io.spray/spray-can_2.11/bundles/spray-can_2.11-1.3.3.jar:/home/fommil/.ivy2/cache/org.ow2.asm/asm/jars/asm-5.0.3.jar:/home/fommil/.ivy2/cache/com.jolbox/bonecp/bundles/bonecp-0.8.0.RELEASE.jar:/home/fommil/.ivy2/cache/io.spray/spray-io_2.11/bundles/spray-io_2.11-1.3.3.jar:/home/fommil/.ivy2/cache/org.apache.lucene/lucene-analyzers-common/jars/lucene-analyzers-common-4.7.2.jar:/home/fommil/.ivy2/cache/org.ow2.asm/asm-commons/jars/asm-commons-5.0.3.jar:/home/fommil/.ivy2/cache/org.scala-lang/scala-compiler/jars/scala-compiler-2.11.6.jar:/home/fommil/.ivy2/cache/com.h2database/h2/jars/h2-1.4.187.jar:/home/fommil/.ivy2/cache/org.apache.commons/commons-vfs2/jars/commons-vfs2-2.0.jar:/home/fommil/.ivy2/cache/io.spray/spray-util_2.11/bundles/spray-util_2.11-1.3.3.jar:/home/fommil/.ivy2/cache/org.scala-lang/scalap/jars/scalap-2.11.6.jar:/home/fommil/.ivy2/cache/org.ow2.asm/asm-tree/jars/asm-tree-5.0.3.jar:/home/fommil/.ivy2/cache/io.spray/spray-http_2.11/bundles/spray-http_2.11-1.3.3.jar:/home/fommil/.ivy2/cache/org.apache.lucene/lucene-core/jars/lucene-core-4.7.2.jar:/home/fommil/.ivy2/cache/org.ow2.asm/asm-util/jars/asm-util-5.0.3.jar:/home/fommil/.ivy2/cache/org.scala-lang.modules/scala-parser-combinators_2.11/bundles/scala-parser-combinators_2.11-1.0.3.jar:/home/fommil/.ivy2/cache/org.scala-lang.modules/scala-xml_2.11/bundles/scala-xml_2.11-1.0.3.jar:/home/fommil/.ivy2/cache/com.typesafe.slick/slick_2.11/bundles/slick_2.11-2.1.0.jar:/home/fommil/Projects/ensime-server/spray-json-shapeless/target/scala-2.11/classes:/home/fommil/.ivy2/cache/com.chuusai/shapeless_2.11/bundles/shapeless_2.11-2.2.0-SNAPSHOT.jar:/home/fommil/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.11.4.jar:/home/fommil/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.11.6.jar:/home/fommil/.ivy2/cache/org.slf4j/jcl-over-slf4j/jars/jcl-over-slf4j-1.7.12.jar:/home/fommil/.ivy2/cache/org.scoverage/scalac-scoverage-runtime_2.11/jars/scalac-scoverage-runtime_2.11-1.0.4.jar:/home/fommil/.ivy2/cache/ch.qos.logback/logback-core/jars/logback-core-1.1.3.jar:/home/fommil/.ivy2/cache/io.spray/spray-json_2.11/bundles/spray-json_2.11-1.3.1.jar:/home/fommil/.ivy2/cache/org.scoverage/scalac-scoverage-plugin_2.11/jars/scalac-scoverage-plugin_2.11-1.0.4.jar:/home/fommil/.ivy2/cache/org.scala-lang.modules/scala-xml_2.11/bundles/scala-xml_2.11-1.0.1.jar:/home/fommil/.ivy2/cache/org.slf4j/slf4j-api/jars/slf4j-api-1.7.12.jar:/home/fommil/.ivy2/cache/ch.qos.logback/logback-classic/jars/logback-classic-1.1.3.jar:/home/fommil/.ivy2/cache/org.slf4j/jul-to-slf4j/jars/jul-to-slf4j-1.7.12.jar:/home/fommil/Projects/ensime-server/jerk/target/scala-2.11/classes:/home/fommil/Projects/ensime-server/testing/simple/target/scala-2.11/classes:/home/fommil/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.11.4.jar:/home/fommil/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.11.6.jar:/home/fommil/.ivy2/cache/org.scoverage/scalac-scoverage-runtime_2.11/jars/scalac-scoverage-runtime_2.11-1.0.4.jar:/home/fommil/.ivy2/cache/org.scoverage/scalac-scoverage-plugin_2.11/jars/scalac-scoverage-plugin_2.11-1.0.4.jar:/home/fommil/.ivy2/cache/org.scala-lang.modules/scala-xml_2.11/bundles/scala-xml_2.11-1.0.1.jar:/home/fommil/Projects/ensime-server/testing/debug/target/scala-2.11/classes:/home/fommil/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.11.4.jar:/home/fommil/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.11.6.jar:/home/fommil/.ivy2/cache/org.scoverage/scalac-scoverage-runtime_2.11/jars/scalac-scoverage-runtime_2.11-1.0.4.jar:/home/fommil/.ivy2/cache/org.scoverage/scalac-scoverage-plugin_2.11/jars/scalac-scoverage-plugin_2.11-1.0.4.jar:/home/fommil/.ivy2/cache/org.scala-lang.modules/scala-xml_2.11/bundles/scala-xml_2.11-1.0.1.jar:/home/fommil/Projects/ensime-server/api/target/scala-2.11/classes:/home/fommil/.ivy2/cache/org.scalariform/scalariform_2.11/jars/scalariform_2.11-0.1.6.jar:/home/fommil/.ivy2/cache/com.github.stacycurl/pimpathon-core_2.11/jars/pimpathon-core_2.11-1.5.0-SNAPSHOT.jar:/home/fommil/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.11.4.jar:/home/fommil/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.11.6.jar:/home/fommil/.ivy2/cache/org.scala-lang.modules/scala-parser-combinators_2.11/bundles/scala-parser-combinators_2.11-1.0.1.jar:/home/fommil/.ivy2/cache/org.scoverage/scalac-scoverage-runtime_2.11/jars/scalac-scoverage-runtime_2.11-1.0.4.jar:/home/fommil/.ivy2/cache/org.scoverage/scalac-scoverage-plugin_2.11/jars/scalac-scoverage-plugin_2.11-1.0.4.jar:/home/fommil/.ivy2/cache/org.scala-lang.modules/scala-xml_2.11/bundles/scala-xml_2.11-1.0.1.jar:/home/fommil/Projects/ensime-server/swank/target/scala-2.11/classes:/home/fommil/.ivy2/cache/org.slf4j/slf4j-api/jars/slf4j-api-1.7.5.jar:/home/fommil/.ivy2/cache/com.typesafe.akka/akka-slf4j_2.11/jars/akka-slf4j_2.11-2.3.9.jar:/home/fommil/.ivy2/cache/com.typesafe/config/bundles/config-1.2.1.jar:/home/fommil/.ivy2/cache/com.typesafe.akka/akka-actor_2.11/jars/akka-actor_2.11-2.3.9.jar -Dscala.usejavacp=true scala.tools.nsc.MainGenericRunner)
```

**Comment by fommil** [comment]
heh, all I can conclude is that this is a bug in the scala code! :smile:

**Comment by fommil** [comment]
https://github.com/scala/scala/blob/ee864c1d77ecbac354f4dae71b247a54d053fbdb/src/repl/scala/tools/nsc/interpreter/ILoop.scala#L58

https://github.com/scala/scala/blob/ee864c1d77ecbac354f4dae71b247a54d053fbdb/src/library/scala/util/Properties.scala#L107

so they must have the wrong prop, which I find unlikely.

**Comment by fommil** [comment]
ok, looks like some 2.11.4 jars slipped in.

**Comment by fommil** [comment]
ok, clearing out scoverage from the ensime project, I get back to the correct version of scala.

But a weird one:

```
Welcome to Scala version 2.11.6 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_45).
```

when my `.ensime` file says

```
 :java-home "/usr/lib/jvm/java-6-oracle"
```

and

```
/usr/lib/jvm/java-6-oracle/bin/java -version
java version "1.6.0_45"
Java(TM) SE Runtime Environment (build 1.6.0_45-b06)
Java HotSpot(TM) 64-Bit Server VM (build 20.45-b01, mixed mode)
```

any ideas why the java home could be getting changed?

**Comment by fommil** [comment]
ok, this is weird. I restarted emacs and did it again and got

```
Failed to created JLineReader: java.lang.NoClassDefFoundError: jline/console/completer/Completer
Falling back to SimpleReader.
Welcome to Scala version 2.11.6 (Java HotSpot(TM) 64-Bit Server VM, Java 1.6.0_45).
```

I wonder if there was some weird caching issue going on. Seems to be working now.

**Comment by fommil** [comment]
btw, I raised the above scala version issue with https://github.com/scoverage/sbt-scoverage/issues/106

**Comment by edani** [comment]
@dangerousben  This looks pretty good to me.
- The error about jline can be silenced by passing the "-Xnojline" option (in ensime-inf-cmd-template, after MainGenericRunner)
- The current behavior is to also include the test classpath (from :test-deps). Do you think it's a good idea or would there be drawbacks?

**Comment by dangerousben** [comment]
On 12 May 2015 at 07:12, Eric Daniel <notifications@github.com> wrote:
> The current behavior is to also include the test classpath (from :test-deps). Do you think it's a good idea or would there be drawbacks?

It seems useful, I assume you'd want :test-targets as well?

**Comment by fommil** [comment]
maybe the REPL function that takes two parameters: module name and includeTests. Walking the dependency graph to build up the list of jars to include on the classpath shouldn't be too hard and would allow users to specify sub selections.

This would be a more general form of `sbt`s `console` command (general because it doesn't require `sbt` and not all our users have `sbt` projects).

**Comment by fommil** [comment]
if you could squash this, it looks good to go (assuming the tests pass... we're having trouble with our CI provider)

**Comment by dangerousben** [comment]
There seems to be an issue with one of the tests locally, am investigating.

**Comment by dangerousben** [comment]
Ok all sorted I think.  Apparently "Test inspector UI" fails under java 8 because the doc urls have changed.

Definitely interested in making this more flexible as described above but as it's likely to take a while I'll make that a separate PR.

**Comment by fommil** [comment]
awesome stuff! I'll be sure to include this in the demo at the Scala Days next month :smile:

**Comment by fommil** [comment]
btw, we have a docker image with the same version of java, emacs and scala used by our CI.

**Pull request merged**
