### PR TITLE
Fix typecheck of new, empty, unsaved file. Improve testing.

### PR DESCRIPTION
**Pull request by aemoncannon**

### CODE REVIEW

**Comment by fommil** [comment]
drone is acting up, I've restarted the jobs

**Comment by fommil** [comment]
weird, I'm not able to restart. Can you just push a change?

**Comment by fommil** [comment]
no need, it's restarting

**Comment by aemoncannon** [comment]
Yeah. Drone gave false positive here. Looks maybe related to the restart.

**Pull request merged**
