### PR TITLE
fix the build

### PR DESCRIPTION
**Pull request by fommil**

### CODE REVIEW

**Comment by fommil** [comment]
Damn, now that each test indexes the scala libs (and j2se), I suspect we're hitting VM limits.

**Comment by rorygraves** [comment]
Will kick Jenkins back into life later on today - should be immune to those limits and/or provide another datapoint.

**Comment by fommil** [comment]
no need, I can move us to the docker infrastructure.

**Comment by fommil** [comment]
```
Finished suite with status 0.
Sending: report to coveralls.io
Sending: OK
The command "test/run_emacs_tests.sh" exited with 1.
```

wtf? Something weird going on.

**Comment by fommil** [comment]
dag nammit... this looks like a bug in emacs24.4!!!

**Comment by aemoncannon** [comment]
@fommil lol. btw, thanks for hacking through all this logistical stuff. let
me know if there's something I can do to be helpful.

**Comment by fommil** [comment]
I'm going to build a 24.3 tonight on Ubuntu Precise, and file a full bug report with emacs, and then get bot our builds using it. Nope, I think we're good thanks :smile:

**Pull request merged**
