### PR TITLE
Fix syntax error in build.sbt

### PR DESCRIPTION
**Pull request by mattiasb**

### CODE REVIEW

**Comment by mattiasb** [comment]
Basically I was getting this whenever i ran (ensime-server-update):
```
/tmp/ensime_update_87764qG/build.sbt:7: error: eof expected but ';' found.
scalaBinaryVersion := "2.10"
^
[error] Error parsing expression.  Ensure that settings are separated by blank lines.
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? q
```

Adding a newline at the right point seems to fix it.

**Comment by mattiasb** [comment]
```
$ sbt --version
sbt launcher version 0.13.1
```

**Comment by fommil** [comment]
We don't support this old version of sbt and besides it should be picking up the build.properties file to use the version we specify. Upgrade your sbt.

**Comment by fommil** [comment]
If you can't upgrade sbt, then use assembly jars as documented on the contributing page.

**Pull request closed without merging**
