### PR TITLE
Handle symlinks properly when assigning source buffers to connections. Resolves ensime/ensime-server#714

### PR DESCRIPTION
**Pull request by aemoncannon**

### CODE REVIEW

**Comment by aemoncannon** [comment]
Why not use Emacs' file-in-directory-p? 
If I have a buffer open: /proj/src/X.scala,
and src is a symlink to /tmp/sources, (file-in-directory-p "/proj/src/X.scala" "/proj") will answer nil, where ensime-dir-contains-file-p will answer t.

**Comment by aemoncannon** [comment]
In other words, file-in-directory-p is testing for physical containment, and ensime-dir-contains-file-p is testing for logical containment.

**Comment by fommil** [comment]
cool! Can you please put the explanation you gave in the PR into the function docs? One day we might forget why we did it this way. And by we, I mean me... in about a week.

**Comment by aemoncannon** [comment]
Sure thing : ) will update.

**Comment by aemoncannon** [comment]
updated doc & squashed.

**Comment by omnisis** [comment]
FYI, I was being affected by this bug.  Just merged aemoncannon's fix into my local ensime-emacs folder re-started emacs and I can load projects with symlinked source dirs now!

**Comment by fommil** [comment]
This will help out with default scalajs cross compile projects

**Pull request merged**
