### PR TITLE
edit-definition-of-type-of-thing-at-point

### PR DESCRIPTION
**Pull request by bomgar**
Jumps to the type of the thing at point.

Implements https://github.com/ensime/ensime-emacs/issues/554

### CODE REVIEW

**Comment by bomgar** [comment]
I guess `ensime-search-sym-pos` is the wrong method here. Any suggestions?

**Comment by fommil** [comment]
nice! Can you please add a test in the existing test for "go to type".

The call to `ensime-rpc-get-type-at-point` should obtain the position information already... is the info not in there?

It would be really nice if this was bound to the typical `M-.` when prefixed with the universal argument, e.g. `M-u M-.` (you know what I mean by universal arguments?).

**Comment by bomgar** [comment]
I'm having trouble finding an existing test. It seems `ensime-edit-definition` is called nowhere.

**Comment by bomgar** [comment]
Ok I've done everything. Great idea with the universal argument.

The ci build seems to be hanging.

**Comment by fommil** [comment]
Looks great! Thank you so much!

**Comment by fommil** [comment]
Btw do you want any ensime stickers?

**Comment by bomgar** [comment]
Sure. Stickers are always good.

**Comment by fommil** [comment]
I'm guessing from your profile that you're in Germany?

@larsrh do you have any ensime stickers left?

**Comment by bomgar** [comment]
Yes I'm in Germany.

**Comment by fommil** [comment]
Lars might not check his mentions. Could you please email him with your contact details? And point him here to explain. I have stickers if he's out of them.

**Comment by larsrh** [comment]
Give me a couple of hours to check my mentions, maybe? :stuck_out_tongue_winking_eye: 

On a related note, I'm currently out of stickers.

**Comment by fommil** [comment]
Ah, well in that case email your contact details to me.

**Pull request merged**
