### PR TITLE
Launch from cask

### PR DESCRIPTION
**Pull request by phillord**
Just a starter for 10 -- it doesn't fix all the problems, some of the tests do not succeed, maybe some do not run, but at least you don't have to set the path up.

### CODE REVIEW

**Comment by fommil** [comment]
thanks! The unit tests are being launched via cask, so they are ok... it's the integration tests that are using their own start script. This isn't really a PR that can be accepted since it doesn't do anything, but it's good to have it around.

**Comment by phillord** [comment]
These are the ones in ensime-test.el? Same issue there, perhaps? If you change `exec emacs` to `exec cask`, then there is at least a vague chance that it will all work.

**Comment by fommil** [comment]
If you want to tackle it all the way through that'd be ace! Will cask create all the autoload files? That's the main reason I've used package.

**Comment by phillord** [comment]
cask can create autoload files yes, and the package descriptor file.

**Comment by fommil** [comment]
yeah, we created the package descriptor already but I couldn't find docs on the autoload, so I build the package and then used `use-package` to ensure the autoloads were built correctly for testing.

**Comment by fommil** [comment]
there is no real reason why we need the shell script if we could launch the tests via cask and it will probably simplify the dot file.

**Pull request closed without merging**
