### PR TITLE
During test suite, show server messages on stdout

### PR DESCRIPTION
**Pull request by edani**
~~Do not merge, I just want to run the CI suite.~~
Increase the verbosity of the test suite and make sure that the server replies to all requests.

### CODE REVIEW

**Comment by fommil** [comment]
@edani btw, you can log in to the server and click the rebuild button at the top :smile:

**Comment by fommil** [comment]
got one!
http://fommil.com/github.com/ensime/ensime-emacs/transient/fd5745fb96d1ebd9bb9854cbeca3761bb45187ae

**Comment by edani** [comment]
@fommil  Great, I'll take a look at that failure.  Also  I tried the "login" button then clicked on "github" but it sent me to a blank page http://fommil.com/api/auth/github.com?code=.......&state=.....   ; after that I still wasn't logged in.

**Comment by fommil** [comment]
oh, that's weird. I'm pretty sure I set it up so that all `ensime` owners had access but I could easily have screwed it up.

**Comment by edani** [comment]
It seems that the server should have received a CompletionsReq event but there's no trace of it. I'll enable more logging on the emacs side but after that we'll need to add more logging on the server side.

**Comment by fommil** [comment]
@edani I've registered you as a user on fommil.com's drone installation (I thought that would happen automatically) so I think you can log in now.

**Comment by fommil** [comment]
@edani btw, if you turn on trace level here https://github.com/ensime/ensime-server/blob/master/server/src/main/scala/org/ensime/server/FramedStringProtocol.scala#L49 in the logback file you'll see everything that the server sees. You might want to remove the line length pruning.

**Comment by edani** [comment]
OK, the server is definitely eating some of the requests... or emacs fails to send them which is hard to believe. This log http://fommil.com/github.com/ensime/ensime-emacs/transient/ff3bedca40ec662727e0f98683bfd7aa621ce1c9  shows one instance of it, near the "WARNING more than one pending message".  Request ID 4 shows up in the emacs log, but not in the server log.

**Comment by fommil** [comment]
Interesting. I wonder if Rory's akka io refactor will make this go away

**Comment by fommil** [comment]
yup, looks like

```
--> (:swank-rpc (swank:symbol-designations /tmp/ensime_test_proj_44v8X/src/main/scala/hello_world.scala 0 184 (var val varField valField functionCall operator param class trait object package implicitConversion implicitParams deprecated)) 4)
```

is never arriving with the protocol handler. And at this stage, it's not even doing any parsing, it's just reading it as a `String`. Very curious!

**Comment by fommil** [comment]
@edani is emacs definitely flushing when it is sending?

**Comment by fommil** [comment]
after some digging, it looks like Emacs doesn't buffer here so there is no need to flush.

For the ease of discussion, this is the complete log of the relevant failure.

```
Starting test: 'Verify re-typecheck on save-buffer.'
Copying /tmp/ensime_test_proj_44ikp/cache to /tmp/ensime_test_proj_44v8X/cache
ENSIME server starting...
05:09:06.524 INFO  None a.e.s.Slf4jLogger - Slf4jLogger started

05:09:06.543 DEBUG EventStream(akka://ENSIME) a.e.EventStream - logger log1-Slf4jLogger started

05:09:06.551 DEBUG EventStream(akka://ENSIME) a.e.EventStream - Default Loggers started

05:09:06.745 INFO  None o.a.c.v.i.StandardFileSystemManager - Using "/tmp/vfs_cache" as temporary files store.

05:09:07.956 INFO  None o.e.s.Server - Starting ENSIME TCP on 127.0.0.1:57051

05:09:07.984 INFO  None o.e.s.Server - Environment:
  OS : Linux
  Java : OpenJDK 64-Bit Server VM 23.25-b01, OpenJDK Runtime Environment 1.6.0_35-b35
  Scala : version 2.11.7
  Ensime : 0.9.10-SNAPSHOT
05:09:07.984 INFO  None o.e.s.Server - creating portfile /tmp/ensime_test_proj_44v8X/cache/port

05:09:08.050 DEBUG akka://ENSIME/system/IO-TCP/selectors/$a/0 a.i.TcpListener - Successfully bound to /127.0.0.1:36270

05:09:08.094 INFO  None o.e.s.Server - ENSIME HTTP on /127.0.0.1
05:09:08.095 INFO  None o.e.s.Server - creating portfile /tmp/ensime_test_proj_44v8X/cache/http

05:09:08.467 DEBUG akka://ENSIME/system/IO-TCP/selectors/$a/1 a.i.TcpListener - Successfully bound to /127.0.0.1:36355

05:09:08.473 INFO  akka://ENSIME/user/IO-HTTP/listener-0 s.c.s.HttpListener - Bound to localhost/127.0.0.1:0
05:09:08.474 DEBUG akka://ENSIME/user/docs o.e.s.DocServer - received handled message Bound(/127.0.0.1:36355)

05:09:08.601 WARN  None c.j.b.BoneCPConfig - JDBC username was not set in config!

05:09:08.601 WARN  None c.j.b.BoneCPConfig - JDBC password was not set in config!

05:09:08.967 INFO  None o.e.i.SearchService - removing 0 stale files from the index

05:09:08.995 INFO  None o.e.i.ClassfileWatcher - Setting up new file watchers

05:09:09.157 DEBUG None o.e.i.SearchService - committing index to disk...

05:09:09.158 DEBUG None o.e.i.SearchService - ...done committing index
05:09:09.162 DEBUG akka://ENSIME/user/project o.e.c.Project - indexed 0 and removed 0

Connecting to Swank on port 57051..
--> (:swank-rpc (swank:connection-info) 1)
05:09:11.286 TRACE None o.e.s.SwankProtocol - (:swank-rpc (swank:connection-info) 1)


05:09:11.288 DEBUG akka://ENSIME/user/$b/handler o.e.s.ConnectionHandler - received handled message IndexerReadyEvent

05:09:11.356 DEBUG akka://ENSIME/user/$b/handler/1 o.e.s.RequestHandler - ConnectionInfoReq
05:09:11.359 DEBUG akka://ENSIME/user/project o.e.c.Project - received handled message ConnectionInfoReq
05:09:11.364 DEBUG akka://ENSIME/user/$b/handler/1 o.e.s.RequestHandler - received handled message ConnectionInfo(None,EnsimeImplementation(ENSIME),0.8.17) in state receive

05:09:11.567 TRACE None o.e.s.SwankProtocol - 000010(:indexer-ready)

<-- (:indexer-ready)
pending rpcs: (1)
Received test event: :indexer-ready
Got :indexer-ready/t, expecting (:connected :compiler-ready :full-typecheck-finished) with guard nil. Ignoring event.
05:09:11.587 TRACE None o.e.s.SwankProtocol - 000083(:return
  (
    :ok (
      :pid nil
      :implementation (
        :name "ENSIME"
      )
      :version "0.8.17"
    )
  )
  1)

<-- (:return (:ok (:pid nil :implementation (:name ENSIME) :version 0.8.17)) 1)
pending rpcs: nil
Received test event: :connected
Received :connected/(:pid nil :implementation (:name ENSIME) :version 0.8.17) expecting (:connected :compiler-ready :full-typecheck-finished) with guard func nil. Waiting for the rest
Connected to ENSIME speaking protocol 0.8.17, please wait while the project is loaded.
pending rpcs: nil
Received test event: :return-value
Got :return-value/(:ok (:pid nil :implementation (:name ENSIME) :version 0.8.17)), expecting (:compiler-ready :full-typecheck-finished) with guard nil. Ignoring event.
05:09:11.859 DEBUG akka://ENSIME/user/$b/handler o.e.s.ConnectionHandler - received handled message SendBackgroundMessageEvent(Initializing Analyzer. Please wait...,105)

<-- (:background-message 105 Initializing Analyzer. Please wait...)
Initializ
05:09:11.875 TRACE None o.e.s.SwankProtocol - 000045(:background-message
  105
  "Initializing Analyzer. Please wait...")

<-- (:compiler-ready)
ENSIME ready. Hacks and glory await!
--> (:swank-rpc (swank:symbol-designations /tmp/ensime_test_proj_44v8X/src/main/scala/hello_world.scala 0 171 (var val varField valField functionCall operator param class trait object package implicitConversion implicitParams deprecated)) 2)
pending rpcs: (2)
Received test event: :compiler-ready
Received :compiler-ready/t expecting (:compiler-ready :full-typecheck-finished) with guard func nil. Waiting for the rest
05:09:11.891 DEBUG akka://ENSIME/user/project/analyzer o.e.c.Analyzer - received handled message FullTypeCheckCompleteEvent in state startup
05:09:11.892 DEBUG akka://ENSIME/user/$b/handler o.e.s.ConnectionHandler - received handled message AnalyzerReadyEvent
05:09:11.894 DEBUG akka://ENSIME/user/$b/handler o.e.s.ConnectionHandler - received handled message FullTypeCheckCompleteEvent
05:09:11.894 TRACE None o.e.s.SwankProtocol - 000011(:compiler-ready)
05:09:11.895 TRACE None o.e.s.SwankProtocol - 00001a(:full-typecheck-finished)
05:09:11.896 TRACE None o.e.s.SwankProtocol - (:swank-rpc (swank:symbol-designations "/tmp/ensime_test_proj_44v8X/src/main/scala/hello_world.scala" 0 171 (var val varField valField functionCall operator param class trait object package implicitConversion implicitParams deprecated)) 2)


<-- (:full-typecheck-finished)
pending rpcs: (2)
Received test event: :full-typecheck-finished
Handling test event: :full-typecheck-finished/(:events (:full-typecheck-finished) :func (lambda (G51391) (ensime-test-run-with-handlers Verify re-typecheck on save-buffer. (ensime-test-with-proj (proj src-files) (let* ((notes (ensime-all-notes))) (ensime-assert-equal (length notes) 0) (find-file (car src-files)) (goto-char (point-min)) (insert lksdjfldkjf ) (save-buffer))))) :is-last nil)
Saving file /tmp/ensime_test_proj_44v8X/src/main/scala/hello_world.scala...
Wrote /tmp/ensime_test_proj_44v8X/src/main/scala/hello_world.scala
--> (:swank-rpc (swank:typecheck-file (:file /tmp/ensime_test_proj_44v8X/src/main/scala/hello_world.scala)) 3)
--> (:swank-rpc (swank:symbol-designations /tmp/ensime_test_proj_44v8X/src/main/scala/hello_world.scala 0 184 (var val varField valField functionCall operator param class trait object package implicitConversion implicitParams deprecated)) 4)
05:09:11.944 TRACE None o.e.s.SwankProtocol - (:swank-rpc (swank:typecheck-file (:file "/tmp/ensime_test_proj_44v8X/src/main/scala/hello_world.scala")) 3)


05:09:12.027 DEBUG akka://ENSIME/user/$b/handler/2 o.e.s.RequestHandler - SymbolDesignationsReq(/tmp/ensime_test_proj_44v8X/src/main/scala/hello_world.scala,0,171,List(VarSymbol, ValSymbol, VarFieldSymbol, ValFieldSymbol, FunctionCallSymbol, OperatorFieldSymbol, ParamSymbol, ClassSymbol, TraitSymbol, ObjectSymbol, PackageS

05:09:12.028 DEBUG akka://ENSIME/user/project o.e.c.Project - received handled message SymbolDesignationsReq(/tmp/ensime_test_proj_44v8X/src/main/scala/hello_world.scala,0,171,List(VarSymbol, ValSymbol, VarFieldSymbol, ValFieldSymbol, FunctionCallSymbol, OperatorFieldSymbol, ParamSymbol, ClassSymbol, TraitSymbo
05:09:12.030 DEBUG akka://ENSIME/user/project/analyzer o.e.c.Analyzer - received handled message SymbolDesignationsReq(/tmp/ensime_test_proj_44v8X/src/main/scala/hello_world.scala,0,171,List(VarSymbol, ValSymbol, VarFieldSymbol, ValFieldSymbol, FunctionCallSymbol, OperatorFieldSymbol, ParamSymbol, ClassSymbol, TraitSymbo
05:09:12.053 DEBUG akka://ENSIME/user/$b/handler/3 o.e.s.RequestHandler - TypecheckFileReq(SourceFileInfo(/tmp/ensime_test_proj_44v8X/src/main/scala/hello_world.scala,None,None))
05:09:12.054 DEBUG akka://ENSIME/user/project o.e.c.Project - received handled message TypecheckFileReq(SourceFileInfo(/tmp/ensime_test_proj_44v8X/src/main/scala/hello_world.scala,None,None))

05:09:12.132 DEBUG akka://ENSIME/user/$b/handler o.e.s.ConnectionHandler - received handled message NewScalaNotesEvent(false,List(Note(/tmp/ensime_test_proj_44v8X/src/main/scala/hello_world.scala,expected class or object definition,NoteError,0,0,1,1)))

<-- (:scala-notes (:is-full nil :notes ((:file /tmp/ensime_test_proj_44v8X/src/main/scala/hello_world.scala :msg expected class or object definition :severity error :beg 0 :end 0 :line 1 :col 1))))
05:09:12.164 TRACE None o.e.s.SwankProtocol - 000115(
  :scala-notes (
    :is-full nil
    :notes ((
        :file "/tmp/ensime_test_proj_44v8X/src/main/scala/hello_world.scala"
        :msg "expected class or object definition"
        :severity error
        :beg 0
        :end 0
        :lin

05:09:13.229 DEBUG akka://ENSIME/user/project/analyzer o.e.c.Analyzer - received handled message TypecheckFileReq(SourceFileInfo(/tmp/ensime_test_proj_44v8X/src/main/scala/hello_world.scala,None,None)) in state ready

05:09:13.230 DEBUG akka://ENSIME/user/$b/handler/2 o.e.s.RequestHandler - received handled message SymbolDesignations(/tmp/ensime_test_proj_44v8X/src/main/scala/hello_world.scala,List(SymbolDesignation(35,35,PackageSymbol), SymbolDesignation(84,88,ParamSymbol), SymbolDesignation(90,103,ClassSymbol), SymbolDesignation(117,1

05:09:13.267 DEBUG akka://ENSIME/user/$b/handler/3 o.e.s.RequestHandler - received handled message VoidResponse in state receive

<-- (:return (:ok (:file /tmp/ensime_test_proj_44v8X/src/main/scala/hello_world.scala :syms ((package 35 35) (param 84 88) (class 90 103) (functionCall 117 124) (object 109 116) (param 152 153) (class 154 157) (param 159 160) (class 161 164) (class 166 169)))) 2)
pending rpcs: (4 3)
WARNING more than one pending message
Received test event: :region-sem-highlighted
Got :region-sem-highlighted/nil, expecting (:full-typecheck-finished) with guard nil. Ignoring event.
pending rpcs: (4 3)
WARNING more than one pending message
Received test event: :return-value
Got :return-value/(:ok (:file /tmp/ensime_test_proj_44v8X/src/main/scala/hello_world.scala :syms ((package 35 35) (param 84 88) (class 90 103) (functionCall 117 124) (object 109 116) (param 152 153) (class 154 157) (param 159 160) (class 161 164) (class 166 169)))), expecting (:full-typecheck-finished) with guard nil. Ignoring event.
05:09:13.318 DEBUG akka://ENSIME/user/$b/handler o.e.s.ConnectionHandler - received handled message ClearAllScalaNotesEvent
05:09:13.329 TRACE None o.e.s.SwankProtocol - 000233(:return
  (
    :ok (
      :file "/tmp/ensime_test_proj_44v8X/src/main/scala/hello_world.scala"
      :syms ((package
          35
          35)
        (param
          84
          88)
        (class
          90
          103)
        (fun
05:09:13.329 DEBUG akka://ENSIME/user/$b/handler o.e.s.ConnectionHandler - received handled message NewScalaNotesEvent(false,List(Note(/tmp/ensime_test_proj_44v8X/src/main/scala/hello_world.scala,expected class or object definition,NoteError,0,0,1,1)))
05:09:13.330 TRACE None o.e.s.SwankProtocol - 000018(:clear-all-scala-notes)

<-- (:clear-all-scala-notes)
<-- (:return (:ok nil) 3)
pending rpcs: (4)
Received test event: :return-value
Got :return-value/(:ok nil), expecting (:full-typecheck-finished) with guard nil. Ignoring event.
05:09:13.334 TRACE None o.e.s.SwankProtocol - 000021(:return
  (
    :ok nil
  )
  3)

<-- (:scala-notes (:is-full nil :notes ((:file /tmp/ensime_test_proj_44v8X/src/main/scala/hello_world.scala :msg expected class or object definition :severity error :beg 0 :end 0 :line 1 :col 1))))
05:09:13.340 TRACE None o.e.s.SwankProtocol - 000115(
  :scala-notes (
    :is-full nil
    :notes ((
        :file "/tmp/ensime_test_proj_44v8X/src/main/scala/hello_world.scala"
        :msg "expected class or object definition"
        :severity error
        :beg 0
        :end 0
        :lin

05:09:13.527 DEBUG akka://ENSIME/user/project/analyzer o.e.c.Analyzer - received handled message FullTypeCheckCompleteEvent in state ready

<-- (:full-typecheck-finished)
pending rpcs: (4)
Received test event: :full-typecheck-finished
Handling test event: :full-typecheck-finished/(:events (:full-typecheck-finished) :func (lambda (G51392) (ensime-test-run-with-handlers Verify re-typecheck on save-buffer. (ensime-test-with-proj (proj src-files) (let ((notes (ensime-all-notes))) (ensime-assert (> (length notes) 0)) (ensime-test-cleanup proj))))) :is-last t)
WARNING no response to messages: (4)
Server connection closed unexpectedly: connection broken by remote peer

Deleting /tmp/ensime_test_proj_44v8X
```

**Comment by fommil** [comment]
I'm tempted to just wait for rory's akka-io refactor. I know he has nearly got something that's working.

**Comment by rorygraves** [comment]
I am very close - I have a akka.io based handler - just cleanup up some initialisation stuff (and want to add some tests....)

**Comment by aemoncannon** [comment]
Could we have a regression from
https://github.com/ensime/ensime-server/pull/593 ?

Looks like the reader is being created repeatedly here:
https://github.com/ensime/ensime-server/blob/master/server/src/main/scala/org/ensime/server/FramedStringProtocol.scala#L27

**Comment by fommil** [comment]
hmm, yeah we buffer the input stream here https://github.com/ensime/ensime-server/blob/master/server/src/main/scala/org/ensime/server/SocketHandler.scala#L37 and then we do create a (non-buffering) reader around that for each message... but I don't see how that would cause a problem. The weird thing is we don't see an exception or log message, so it's like it just disappears entirely.

Very strange.

**Comment by edani** [comment]
Ah, this is the same problem as #593.  InputStreamReader can read more then one character at a time so there should be only one per stream.

**Comment by aemoncannon** [comment]
This failure behavior seems familiar. If InputStreamReader does any
buffering internally, it could slurp up the current message *and* the one
immediately after it. We throw the reader away. The trailing message is
lost.

**Comment by fommil** [comment]
:smile: cool! sounds like it might be worthwhile putting in a little fix until the akka-io refactor is ready. I didn't realise that `InputStreamReader` could perform internal buffering.

I'll put a PR together now. Thanks for the debugging @edani !! Is there any way this could be packaged up so we can flick a switch for the future?

**Comment by rorygraves** [comment]
Crud, good spot gents.

**Comment by rorygraves** [comment]
akka.io changes will remove all of that, but I'm not 100% happy with the changes yet - so definately PR this for now.

**Comment by edani** [comment]
yes, I'll leave the debugging code in  and clean it up (do we always want to turn it on during tests?). Also I'll see if I can turn the check for unanswered requests into an error.

**Comment by fommil** [comment]
Yeah, best keep it always on during tests

**Comment by edani** [comment]
All done. This should catch InputStreamReader-related regressions in the future.  It's difficult to make unit tests catch all replies deterministically so I just added a 10-second wait if there are pending messages.

**Comment by fommil** [comment]
truly fantastic stuff, this will save us all hours/days of hunting!

Once rory's akka-io stuff gets merged, the logging for `org.ensime.server.SwankProtocol` will need to be updated. @rorygraves what's the new equivalent?

**Pull request merged**
