### PR TITLE
Rename ensime-dir-contains-file-p to ensime-path-includes-dir-p. Add tests.

### PR DESCRIPTION
**Pull request by aemoncannon**
I feel like this name better describes what the function is actually doing.

### CODE REVIEW

**Comment by fommil** [comment]
I'm running that again incase it was a transient. I don't see how this could have broken anything :confused:

**Comment by aemoncannon** [comment]
Hrm, I sense it's something unrelated to my PR. I will take a look.

**Comment by aemoncannon** [comment]
I can repro locally now. It only crops up with the newer protocol. Stay tuned.

Btw added elisp to dump backtraces in the event of elisp exceptions (doesn't help in this case, but might be useful later)

**Comment by aemoncannon** [comment]
@fommil @edani  I think there's just one failing assertion left. In the 'expanding parameters' test. Most of this is fallout from the protocol update, which for some reason (I'm guessing order-of-PR-merging) was not caught by the test suite. Should have it cleaned up soon.

**Comment by fommil** [comment]
:smile:

**Comment by aemoncannon** [comment]
Thought for sure that was the last of it. Hung on formatting test just now. Hrmmm

**Comment by aemoncannon** [comment]
Fixed formatting, semantic highlighting failing now

**Comment by aemoncannon** [comment]
Woo! Finally. Merging.

**Pull request merged**
