### PR TITLE
Fixed inserting in import groups at point-min

### PR DESCRIPTION
**Pull request by bomgar**
Should fix https://github.com/ensime/ensime-emacs/issues/523

The importing code is really hard to get right. Isn't this something the server could do?

### CODE REVIEW

**Comment by fommil** [comment]
yeah I agree... there might be a ticket there. would you be interested in hacking on that on the server side? We have a pretty clear refactoring api and client support.

**Comment by bomgar** [comment]
I'm interested in doing that but I'm not sure if I have enough time. I might give it a try.

**Comment by fommil** [comment]
https://github.com/ensime/ensime-server/issues/1401 marked as externally blocked, no reason we can't do it ourselves

**Comment by bomgar** [comment]
In the meantime this fix should still be good. I'm not sure about the CI build but I don't think it has something to do with my changes.

**Comment by fommil** [comment]
Great thanks! The build machines are now store again but sadly our Emacs tests are just really flakey.

**Pull request merged**
