### PR TITLE
Provide hint message for dwim commands

### PR DESCRIPTION
**Pull request by ashawley**
Suggest that the dwim test commands can be run in a test source
file to avoid getting prompted for inputs.

Here's an example of one of the messages when a dwim command is
not run from a test source file:

    "Run ‘C-c C-b o’ from a test file to avoid the prompts"

### CODE REVIEW

**Comment by fommil** [comment]
I'm not sure about this... it can be a bit annoying and is easily fixed if the user reads the docs.

**Comment by ashawley** [comment]
I couldn't find it in the doc.  Those commands don't have docstrings, either.  However, maybe I wasn't looking in the right place.

Regardless, my point isn't about the documentation, anyway.  Giving users suggestions on what they should have done is just good Emacs etiquette, along the same lines as ENSIME itself (`ensime-startup-notifications`, `ensime-troubleshooting`, `ensime-goto-impl', the compatibility check for`ensime-server-jars`).

**Comment by fommil** [comment]
maybe we should add good docstrings instead?

**Comment by fommil** [comment]
(I tend to make it noisy when people keep asking about it on gitter/twitter/SO... but I wish we didn't have to do that)

**Comment by ashawley** [comment]
> maybe we should add good docstrings instead?

Why not all three? In addition to messages in the echo area, I'm happy to work on documentation and docstrings, as well.

**Comment by fommil** [comment]
Ok, let's do that

**Comment by ashawley** [comment]
Ok, done

**Comment by fommil** [comment]
nice, thanks again!

**Pull request merged**
