### PR TITLE
#622 Omit company candiates like: CollectionMapper$ListClass

### PR DESCRIPTION
**Pull request by yangwen0228**
#622 Omit company candidates like:
CollectionMapper$ListClass
CollectionMapper$ListType
JSpinner$ListEditor

### CODE REVIEW

**Comment by fommil** [comment]
Cool! But I think we probably want to do this server side rather than hacking it on the client. Do you need help to see where to do this? Join the `ensime/ensime-server` gitter room to ask questions and/or create a ticket on the server and we can talk there.

**Comment by fommil** [comment]
in fact, this would be a good complement to https://github.com/ensime/ensime-server/issues/354 (i.e. exclusion list for completions... we could allow the user to provide a custom config file with their preferred exclusion regexes once https://github.com/ensime/ensime-server/issues/1346 is ready).

**Comment by fommil** [comment]
have a look on the server tracker for "completion" to see what other ideas we've had in the past.

**Comment by fommil** [comment]
in fact, we do really want this so I'll create the ticket, it'd be awesome if you could hack on it!

**Comment by jozi-k** [comment]
N.B. fix for #501 was also part of this pr.

**Comment by fommil** [comment]
oh, was that not merged already in https://github.com/ensime/ensime-emacs/pull/620/files ?

**Comment by yangwen0228** [comment]
Thank you! Of course I'd like to join the `ensime/ensime-server` gitter room. Since last time I hack on the disconnect issue, I've learned quite a lot Scala from the book 'Programming in Scala' which you recommended. And I really like Scala. It's so concise, flexible and powerful! Sometimes, it's just like some lisp code in Java style. However, I still need some time to learn the ensime-server.
BTW, I find that sometimes, when I type "myA", ensime-company completes with: `main(args: java.lang.String[])`. And sometimes other things like `finalize ...`. It's very weird. So I wrote this to exclude candidates that not begins with prefix:
```
(defun ensime-get-completions-async
    (max-results case-sense callback)
  (ensime-rpc-async-completions-at-point
   max-results case-sense
   (lexical-let ((continuation callback))
     (lambda (info)
       (let* (name
              (prefix (ensime-completion-prefix-at-point))
              (candidates (remove-if
                           '(lambda (candidate)
                              (setq name (getf candidate :name))
                              (or (string-match "\\$" name)
                                  (not (string-match prefix name))))
                           (plist-get info :completions)))
              (candidates (ensime--annotate-completions candidates)))
         (funcall continuation candidates))))))
```

**Comment by fommil** [comment]
That's very weird. If you could write a test in the server that would be useful. I wonder if you are getting yasnippet completions by accident.

**Comment by yangwen0228** [comment]
It's weird. Finally, I find the reason. If the code contains Chinese chars, even in the comments. This phenomenon will occur. I think this is caused by the different calculation methods of string length between English and Chinese. And the results is as follows:

**Comment by fommil** [comment]
Oh I've seen that too... UTF8 in comments can mess up the compiler's range calcs. Maybe specifying the encoding would help but otherwise you may need to fix upstream. I can help with that. Raise a scala bug with a minimal repro and copy me in.

**Pull request closed without merging**
