### PR TITLE
Add tests of inspector ui.

### PR DESCRIPTION
**Pull request by aemoncannon**

### CODE REVIEW

**Comment by fommil** [comment]
```
Starting test: 'Test inspector ui.'
ENSIME server starting...
Server connection closed unexpectedly: connection broken by remote peer
```

**Comment by aemoncannon** [comment]
I'm seeing some weird GitHub stuff this morning. Pushing commits that
aren't showing up on the PR

**Comment by fommil** [comment]
did you mean to disable coveralls?

**Comment by aemoncannon** [comment]
yeah, i'm seeing very mysterious failures on this PR. grasping at straws

**Comment by fommil** [comment]
hmm, yeah, it's a weird one all right. Is is timing out for you locally as well?

**Comment by aemoncannon** [comment]
No. Works every time : (   Working theory: failing an assertion due to java
version (urls generated differently), then our harness is choking somehow.

**Comment by fommil** [comment]
what if you use the docker image to run the tests on your machine? BTW, send me a public ssh key and I'll give you access to the linux VPS we're using for the CI.

**Comment by aemoncannon** [comment]
Btw, 99% sure it's coveralls breaking the 24.4 tests (consistently). Been strapped for time lately but hopefully can find the problem code this weekend -- guessing it's some funny macro in inspector.el that we've never run in tests before.

**Comment by fommil** [comment]
Interesting. You can exclude not one file for now

**Comment by aemoncannon** [comment]
FYI disabling coveralls for ensime-inspector.el did the trick. I'll try removing the exception once edani's macro PR goes in

**Pull request merged**
