### PR TITLE
Don't prompt for config filename when it's known

### PR DESCRIPTION
**Pull request by greenrd**
Fixes ensime/ensime-server/#937

### CODE REVIEW

**Comment by fommil** [comment]
Thanks! You could have bloody waited until after scala days, now I have to update the contributor list :-P

Did you run the tests locally? I have zero faith in the shippable build and I plan to replace it with drone immediately.

**Comment by fommil** [comment]
I just tried this out... I opened up my project base directory with `dired` and typed `M-x ensime` but it still prompted me for the config file. Is that expected?

**Comment by greenrd** [comment]
You have to customize `ensime-auto-generate-config` to `t`. This pull request only covers cases when the config is auto-generated.

**Comment by fommil** [comment]
@greenrd what do you think about making the auto discovery independent of the auto-generated sbt? I'd quite like this feature, but not the auto generate. A separate `defvar` for the option, on by default.

**Comment by fommil** [comment]
I like this but I'd like to get the "default to autodetected file" working for starting the server/REPL if thats possible. See the linked PR for more context.

**Comment by fommil** [comment]
@greenrd are you happy to make the requested changes here or in a follow up?

**Comment by greenrd** [comment]
@fommil yes - I've been busy moving house recently, but I'll try to look at it this weekend.

**Comment by fommil** [comment]
no problem, take a few weeks its not urgent :smile:

**Comment by fommil** [comment]
ping

**Comment by fommil** [comment]
btw, just incase you weren't aware, you can get the config for the current buffer by doing this

```
  (let* ((connection (ensime-connection))
         (config (ensime-config connection))
  ...)
```

it won't work for non-sources, but I don't think it should be too hard to fix that (might involve a hack involving looking at the `:root-dir` after all source checks fail).

**Comment by fommil** [comment]
Ping

**Comment by greenrd** [comment]
I'm not going to have a chance to look at this until I go on holiday next Tuesday.

**Comment by fommil** [comment]
@greenrd new houses, holidays?! Anybody would think you had a life outside scala :-)

No problem, I'm just doing the pinging rounds on all open PRs. Leave it until after your hols.

**Comment by fommil** [comment]
@greenrd ! ping

btw, somewhat relevant is #253

**Comment by fommil** [comment]
I'm cherry picking this onto a PR that I hope to raise tonight.

**Pull request closed without merging**
