### PR TITLE
travis => shippable

### PR DESCRIPTION
**Pull request by fommil**

### CODE REVIEW

**Comment by aemoncannon** [comment]
Yeah!

**Comment by fommil** [comment]
Everything green! But coveralls is not working, probably due to https://github.com/sviridov/undercover.el/issues/7

**Comment by fommil** [comment]
interesting. I got transient failures in `Test completing imports.` I wonder if it was my removal of some awaiting last week.

**Comment by fommil** [comment]
uuugh, looks like the indexer sometimes suggests the VectorBuilder instead of Vector.

**Comment by fommil** [comment]
doh! Thought I'd merged this.

**Pull request merged**
