### PR TITLE
Added faces for deprecated symbols

### PR DESCRIPTION
**Pull request by ale64bit**
Added the face support for corresponding PR in `ensime-server`.

### CODE REVIEW

**Comment by fommil** [comment]
I've kicked off a new build, new server should be available now.

**Comment by fommil** [comment]
ok, this is passing the tests.

Can you please squash? And it would be great if you could update the existing semantic highlighting test to include this. The emacs tests are not just for the emacs code, it's also useful to have additional integration tests here.

**Comment by ale64bit** [comment]
@fommil Done. Sometimes I get this error when running the tests:
```
ensime-macros.el: `flet' is an obsolete macro (as of 24.3); use either `cl-flet' or `cl-letf'.
ensime-inf.el: (lambda (x) ...) quoted with ' rather than with #'
ensime-goto-testfile.el: `labels' is an obsolete macro (as of 24.3); use `cl-labels' instead.
ensime-notes.el: `labels' is an obsolete macro (as of 24.3); use `cl-labels' instead.
(invalid-read-syntax ))  load-with-code-conversion
```
What about it? 

P.S.: Sorry for inexperience; I started using emacs a week ago.

**Comment by fommil** [comment]
we need some code cleanup by the sounds of it

**Comment by fommil** [comment]
Interesting, I think you might have introduced a regression because I've never seen this error before

```
(invalid-read-syntax )) load-with-code-conversion
```

It's so weird that I suspect a typo, extra or missing bracket somewhere.

**Comment by ale64bit** [comment]
@fommil oops, sorry about that. Fixed and tested.

**Pull request merged**
