### PR TITLE
Fixes https://github.com/ensime/ensime-server/issues/769 (can see ENSIME...

### PR DESCRIPTION
**Pull request by alpeb**
...-server classpath in completion options)

Problem is properties set on the command-line override the setting we instantiate the presentation compiler with. And since after testing with scala 2.9, 2.10 and 2.11 without this property didn't seem to affect Ensime, we're killing it.

### CODE REVIEW

**Comment by fommil** [comment]
Thanks for looking into this, one line but a lot of research!

@alpeb do the tests pass for you locally? just run the shell script and wait a while

**Comment by alpeb** [comment]
@fommil Running `test/run_emacs_tests.sh` complains about not being able to load `./dotemacs_test.el`,   and when running from inside `test` then `require(ensime)` fails. What's the proper way of running the tests? Thanks!

**Comment by fommil** [comment]
@alpeb oh that was refactored recently and a bug crept in. Change the `./dotemacs_test.el` to `test/dotemacs_test.el` and rerun (please include this in your PR)

**Comment by alpeb** [comment]
I traced the test failure back to https://github.com/ensime/ensime-emacs/blob/master/ensime-test.el#L95 where the ensime test config is created. Now that `usejavacp` is gone we need to provide here a suitable `compile-deps` setting pointing to the scala lib. I see how `ensime-sbt` generates that entry for new projects, but seems tough to do in elisp...

**Comment by fommil** [comment]
aaah, you mean our emacs test project doesn't have scala in its dependency list? The scala-lib jar should be one of the entries in the classpath file so you could read the file, split on the platform's path separator, and then grep for scala-library. How's your elisp? I'm sure @edani or @aemoncannon could help out if we ask nicely :smile:

**Comment by alpeb** [comment]
Yea that's what I meant. You're right, I've just spotted the classpath file. I'm planning on learning elisp, so this might be a nice exercise for me :)

**Comment by fommil** [comment]
@alpeb hi, we are now seeing a similar problem in the other tests (which are now part of the server CI), so the priority of getting this fixed just got bumped :smile:

Are you actively looking at fixing this or would you like one of us to take over adding `scala-library` to the `.ensime` of the test files?

**Comment by alpeb** [comment]
hey @fommil, I spent the week learning elisp, so let me give this a try today.

**Comment by fommil** [comment]
@alpeb sweet! And there will be plenty more opportunities to help out, not time wasted :wink:

**Comment by fommil** [comment]
@alpeb this might help you (bit of elisping before I go to sleep :wink:)

```elisp
(defun ensime--extract-scala-library-jar ()
  (with-temp-buffer
    (insert-file-contents
     (ensime--classpath-file ensime--test-scala-version))
    (--first
     (string-match (concat "/scala-library-" ensime--test-scala-version ".jar") it )
     (split-string (buffer-string) ensime--classpath-separator 'omit-nulls))))
```

**Comment by fommil** [comment]
sorry @alpeb I was so close, and I really needed to fix the build. Please rebase and the one-liner should work :smile:

**Comment by fommil** [comment]
@alpeb and by rebase, I mean rebase off my branch. Travis is having some troubles turning green.

**Comment by alpeb** [comment]
That's cool @fommil . I rebased off your branch, then had to rebase against this branch in order to push. Not sure if I did something wrong, or your branch has conflicts with the master upstream. Tests did pass locally I think (didn't end up with an error and returned to command line without any message).

**Comment by fommil** [comment]
Cool thanks. Looks like you did a merge, rather than a rebase. Just type git rebase now. Travis tests are still failing, I've either introduced a new regression or we're hitting the limits of the virtual machines. Adding the scala libraries increases the load on the server.

**Comment by alpeb** [comment]
I think the merge problem was just I had an outdated branch. Seems fixed now. As for the test, `ensime-fast-suite` runs first and doesn't create a temporary project (like `ensime-slow-suite` does afterwards), and so there is no classpath file, which makes extract-scala-library-jar die.

**Comment by fommil** [comment]
you can `git pull --rebase upstream master` now. Yeah, there is a comment in the `fast-suite` to this effect now.

**Comment by fommil** [comment]
Awesome! This is possibly the most (necessary) research I've ever seen go into a one line change :smile:

**Comment by alpeb** [comment]
Wohoo! Looking forward to keep on contributing!

**Comment by fommil** [comment]
Now that Woah, I know Elisp

you can have a look at https://github.com/ensime/ensime-server/labels/Emacs

**Comment by alpeb** [comment]
Haha that's funny. Will do for sure.

**Comment by fommil** [comment]
awesome, that is now disted and I can see the bug is fixed :smile:

**Pull request merged**
