### PR TITLE
Find uses of symbol at point

### PR DESCRIPTION
**Pull request by bomgar**
It actually does something. (Helm only)

The code is not final yet. I create this pull request so anyone else working on it can see what i've done so far.

### CODE REVIEW

**Comment by yyadavalli** [comment]
@bomgar Do you think we can generalize the format function? If yes, we might be able to reuse the formatted collection with `completing-read` or `ido` for classic and `ivy-read` for ivy.

**Comment by bomgar** [comment]
That should be possible. 
Also it would be awesome to render the line where the usage was found.

**Comment by fommil** [comment]
you're just trying to get me to use Helm, aren't you!

**Comment by fommil** [comment]
"classic" should just dump out to a grep buffer

**Comment by bomgar** [comment]
I hope I can finish it this weekend. Maybe I add the classic  version as well 😄

**Comment by fommil** [comment]
that'd be super awesome. BTW, please check the protocol version string

**Comment by bomgar** [comment]
I also see the benefit a compile buffer provides. Maybe a fallback to the classic version with the universal-argument?

**Comment by fommil** [comment]
so many of our features should be rewritten to use that. `ensime-search` should work this way too.

**Pull request merged**
