### PR TITLE
Fix auto-generate code path in my previous commit

### PR DESCRIPTION
**Pull request by greenrd**
This time I've finally actually tested this code path!

### CODE REVIEW

**Comment by fommil** [comment]
cool, thanks. It's really tough to test some of this stuff.

**Comment by fommil** [comment]
@greenrd can you please have a look at the backquote approach to avoid a global?

**Comment by fommil** [comment]
(I'll merge for now since this is a functional fix)

**Comment by fommil** [comment]
@greenrd can you please send a PR with the suggested fix to remove the global variable?

**Comment by greenrd** [comment]
@fommil Sure, will do that on Sunday.

**Comment by fommil** [comment]
@greenrd did you ever get around to reading the elisp reference manual? It's actually a really good read! I loved it. There is a preview release for the Emacs 25 manual if you are interested http://ftp.newartisans.com/pub/emacs/manuals/

**Pull request merged**
