### PR TITLE
The Purge

### PR DESCRIPTION
**Pull request by yyadavalli**

### CODE REVIEW

**Review by fommil — APPROVED** [review]

**Comment by tarsius** [comment]
Please consider renaming the **branch** `2.0` to `master` and `3.0` to `next`.

**Comment by yyadavalli** [comment]
@tarsius do you have a specific reason for that. We have it as `3.0` and `2.0` to align with [ensime-server](https://github.com/ensime/ensime-server)

**Comment by tarsius** [comment]
As the maintainer of the Emacsmirror I run into many issues where someone decides to break with the conventions, such as having a branch named `master`, or following elisp header conventions, or not bundling third-party libraries, or not using homegrown licenses. Usually the maintainers have, or believe to have, some good reason to depart from the conventions, but often it just means that others will have to deal with those idiosyncrasies.

I have already done this in this case. So I don't don't mind if you keep things as-is - I just though I would point out that this is not optimal. It would actually be more work for me if you did revert to follow the conventions (but not very much).

**Comment by yyadavalli** [comment]
Sure, i'll wait for the other maintainers to comment and rename based on their opinion. I'll ping you if we do so. Let me know if I can do something to make is easy for you to account for the changes.

/cc @fommil @bomgar @iravid

**Comment by tarsius** [comment]
It's not that what you have done doesn't make sense. So stick to it if you prefer. Really.

> Let me know if I can do something to make is easy for you to account for the changes.

No additional action needed - I will see how this is resolved.

**Comment by iravid** [comment]
@yyadavalli @tarsius My only opinion here is playing nice with the ecosystem. I'd rather see more magit features rather than have @tarsius spend time on workarounds ;) 

`master`/`2.0` and `next`/`3.0` are all the same to me :-)

**Comment by fommil** [comment]
I think that will be automatically compatible with melpa, if anybody wants to make the necessary changes. Just make sure `master` is the "default" branch.

**Comment by yyadavalli** [comment]
Since changing branch would only add more work for @tarsius at this point, I'm leaving them as is

**Pull request merged**
