### PR TITLE
Ivy support for show uses

### PR DESCRIPTION
**Pull request by yyadavalli**

### CODE REVIEW

**Comment by fommil** [comment]
Btw, the protocol is changing again tomorrow to account for line previews. Sorry.

**Comment by yyadavalli** [comment]
Saw that, will update as soon as that's merged in.

_Sent from my OnePlus ONEPLUS A5000 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by fommil** [comment]
just let me know when it's non-WIP and I'll merge

**Comment by yyadavalli** [comment]
All good, you can merge it

**Pull request merged**
