### PR TITLE
Small fixes

### LINKED ISSUE #332: Stop closing my windows - too many ensime functions use (delete-window)
I frequently split my frame in to two windows, sometimes three or four.

Various functions in ensime use (delete-window) in their when their window is no longer to be displayed.

Off the top of my head, *ensime-compilation-result* will kill its window when you hit q, and so does the buffer that appears after invoking (ensime)

In comparison, many built in emacs things (like ibuffer, or buffer-menu, or package-menu) do not affect close windows if they did not create them.

A simple reproduction: open a frame with one window. split that window. invoke M-x ensime. second window disappears.

Desired behaviour - don't close windows that you didn't open. Possible additional behaviour: don't close windows inside process sentinels - this leads to windows magically disappearing when you're doing something else, which is quite disruptive.

### LINKED ISSUE #346: ensime-copy-type-at-point
variant of type-at-point that puts the type into the kill ring, would have been really handy for me today... I'm sure it's trivial to implement.

### PR DESCRIPTION
**Pull request by fommil**
@aemoncannon are you ok if I rename `ensime-print-type-at-point`? and also this closes #346 

@greenrd can you have a look where I remove the global variable? I think that's right, but I'm no elisp expert.

addresses one use of #332

### CODE REVIEW

**Comment by aemoncannon** [comment]
lgtm.

**Comment by fommil** [comment]
@lunaryorn I did a quick google to check if anybody was using this function, it turns out you were, so I added a `defalias` so it doesn't break your config.

**Comment by lunaryorn** [comment]
That's nice, thank you very much, but I'm not actually using the .emacs.d repo anymore; it's just left for archiving.  I'm on spacemacs now and the .spacemacs.d repo is my config now 😎

**Comment by fommil** [comment]
@greenrd I tried it out with the auto generate and it seems to work. I've never actually used `ensime-auto-generate-config`, it's pretty neat. It just occurred to me that it can be used in `.dir-locals.el` which means opt-in per project! :smile_cat: 

FYI this is my `.dir-locals.el` in `ensime-server`

```elisp
((nil . ((yatemplate-owner . "ENSIME Authors")
         (yatemplate-license . "GPL 3.0")
         (ensime-auto-generate-config . t))))
```

and so I don't get pestered about these all the time, I have in my `init.el`

```elisp
(put 'yatemplate-owner 'safe-local-variable #'stringp)
(put 'yatemplate-license 'safe-local-variable #'stringp)
(put 'ensime-auto-generate-config 'safe-local-variable #'booleanp)
```

**Pull request merged**
